name: Manual Map Refresh

on:
  workflow_dispatch:  # This allows manual triggering from GitHub UI

jobs:
  refresh-map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install folium geopy
          
      - name: Generate map
        run: python scripts/generate_map.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/maps/community_map.html
          git commit -m "Update map via manual refresh" || echo "No changes to commit"
          git push 