name: Manual Map Refresh

on:
  workflow_dispatch:  # This allows manual triggering from GitHub UI

jobs:
  refresh-map:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install folium geopy
          
      - name: Generate map
        run: python scripts/generate_map.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/maps/community_map.html
          git commit -m "Update map via manual refresh" || echo "No changes to commit"
          git push
          
      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1 