name: Sync Map Data

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger
  
jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests folium geopy
        
    - name: Sync data and update map
      env:
        SHEET_URL: ${{ secrets.SHEET_URL }}
      run: |
        python scripts/sync_sheet_data.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/data/community_map_data.json assets/maps/community_map.html
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update map data from Google Sheet" && git push) 