name: Update Community Map

on:
  repository_dispatch:
    types: [map_update]

jobs:
  update-map:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install folium geopy
    
    - name: Generate map
      run: python scripts/generate_map.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/data/community_map_data.json assets/maps/community_map.html
        git commit -m "Update community map" || exit 0
        git push 